name = "expense-tracker"
main = "src/index.ts"
compatibility_date = "2025-01-01"
account_id = "0835b81da7b08adcc3f63be70c710f65"

[observability]
enabled = true

[assets]
directory = "./frontend/dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "expense-tracker-db"
database_id = "c37c92ed-0509-4dbe-90af-d8f35d8382dc"

[vars]
FRONTEND_URL = "https://expense-tracker.md-muntasir2700.workers.dev"